[0m20:36:04.309806 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC82706550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC82B56F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC82B57B50>]}


============================== 20:36:04.313741 | 1faee4d4-8ecb-41f3-be9f-cb6914fe29cb ==============================
[0m20:36:04.313741 [info ] [MainThread]: Running with dbt=1.8.8
[0m20:36:04.314246 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\pavan\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:36:19.733328 [debug] [MainThread]: Starter project path: C:\Users\pavan\anaconda3\Lib\site-packages\dbt\include\starter_project
[0m20:36:19.765124 [info ] [MainThread]: 
Your new dbt project "DBT_SNOWFLAKE" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:36:19.765124 [info ] [MainThread]: Setting up your profile.
[0m20:36:58.361501 [error] [MainThread]: Encountered an error:

[0m20:36:58.367983 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\pavan\anaconda3\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\anaconda3\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\anaconda3\Lib\site-packages\dbt\cli\main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\pavan\anaconda3\Lib\site-packages\dbt\task\init.py", line 347, in run
    self.setup_profile(profile_name)
  File "C:\Users\pavan\anaconda3\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    adapter = self.ask_for_adapter_choice()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\anaconda3\Lib\site-packages\dbt\task\init.py", line 243, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\anaconda3\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\anaconda3\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m20:36:58.371497 [debug] [MainThread]: Command `dbt init` failed at 20:36:58.371497 after 54.13 seconds
[0m20:36:58.372528 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC82B056D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC82B56D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002CC82B56CD0>]}
[0m20:36:58.372528 [debug] [MainThread]: Flushing usage events
